#!/bin/bash

# Uses docker-compose to build then run what you specify, but in the up-state (attaches ports)

# Remove any containers with the same name that are already running to avoid collision
docker-compose stop $1

docker-compose build $1 && docker-compose up $1
