#!/bin/bash

# Runs the container called `temp`
# Remove any containers with the same name that are already running to avoid collision

docker stop tempRunning
docker rm tempRunning

docker run --rm -it --name tempRunning temp
